### ISSUE TITLE
To-Do tasklist 📋

### ISSUE THREAD

**Issue by soofg** [soofg/Matching-App#1]
# **My To Do's** 

> A overview of my tasks 😋

- [x] Make Wireframes (profile, filtering, dishes, favorites/save)
- [x] Finish my part of the styling
- [x] Connect to a database
- [x] Make collection with some dishes in database
- [x] Make a icon for matching-app
- [ ] Make filtering work
- [ ] Make favorite/save dish work
- [x] Research topic Minify
- [ ] Start trying to minify code
- [ ] Try to regularly push my commits to GitHub

_Changes can / will be made in the future :)_
